### ISSUE TITLE
Ngrok only updates latest/edge

### ISSUE THREAD

**Issue by aradkdj** [ngrok/snap-ngrok#21]
Hi, not sure if a real issue or just a miscommunication. I'm currently on v3/stable, which points to 3.1.0 on snapcraft, and I could not help but notice that the recently merged updates seemed to update latest/edge, not v3/stable. Will the updates trickle down to v3/stable or should I migrate to the spooky-named latest/edge?

**Comment by krwenholz** [comment]
Hi @aradkdj! We just got behind on syncing the updates across channels. v3/stable should be updated this week. Sorry for the confusion!

**Comment by krwenholz** [comment]
`v3/stable` is now updated. We tidied our release docs, so this shouldn't lag as much going forward.
